In [4]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
vectorizer = TfidfVectorizer()
query = ['arts']

In [6]:
labels = np.array(['Lausanne', 'Bern', 'Montreux', 'Zurich','Fribourg'])

corpus = [
    'Lausanne is a great city for arts and arts',
    'Bern is quite nice for history and arts',
    'If you like music, you should go to Montreux',
    'This location is good for arts',
    'Fribourg is  a great city'
    ]

In [7]:
vectorizer = CountVectorizer()
transformer = TfidfTransformer()

trainVectorizer = vectorizer.fit_transform(corpus)
testVectorizer = vectorizer.transform(query)

transformer.fit(trainVectorizer)
X = transformer.transform(trainVectorizer)

transformer.fit(testVectorizer)

Y = transformer.transform(testVectorizer)

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
cosine_similarity(X,Y)

array([[ 0.5704729 ],
       [ 0.27652929],
       [ 0.        ],
       [ 0.326226  ],
       [ 0.        ]])

In [10]:
vals = cosine_similarity(X,Y).flatten()

In [11]:
import numpy as np
np.argsort(vals)

array([2, 4, 1, 3, 0])

In [12]:
indexes = np.argsort(vals)[-3:][::-1]
vals[indexes]

array([ 0.5704729 ,  0.326226  ,  0.27652929])

In [13]:
indexes

array([0, 3, 1])

In [14]:
labels[indexes]

array(['Lausanne', 'Zurich', 'Bern'],
      dtype='<U8')

In [15]:
vals[indexes]

array([ 0.5704729 ,  0.326226  ,  0.27652929])

In [16]:
output = zip(labels[indexes],{'score' : vals[indexes]})

In [17]:
output