In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
#vectorizer = TfidfVectorizer()
query = ['Cheese chocolate Cream']
#query = ['festival jazz music']
#query = ['watches lux']

In [3]:
import pickle
cities_info = pickle.load(open("../cities_new.p", "rb"))
labels = np.array(list(cities_info.keys()))
corpus = np.array(list(cities_info.values()))
len(corpus)

54

In [4]:
vectorizer = CountVectorizer()
transformer = TfidfTransformer()

trainVectorizer = vectorizer.fit_transform(corpus)
testVectorizer = vectorizer.transform(query)

transformer.fit(trainVectorizer)
X = transformer.transform(trainVectorizer)

#transformer.fit(testVectorizer)

Y = transformer.transform(testVectorizer)

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
cosine_similarity(X,Y)

array([[ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.00463245],
       [ 0.        ],
       [ 0.00767921],
       [ 0.        ],
       [ 0.00233185],
       [ 0.        ],
       [ 0.        ],
       [ 0.01552456],
       [ 0.        ],
       [ 0.        ],
       [ 0.00232441],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.00264161],
       [ 0.0339686 ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.01671703],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.00462506],
       [ 0

In [7]:
vals = cosine_similarity(X,Y).flatten()

In [8]:
import numpy as np
np.argsort(vals)

array([ 0, 28, 29, 30, 31, 33, 34, 35, 36, 37, 38, 27, 39, 41, 42, 43, 45,
       46, 47, 48, 49, 50, 51, 40, 52, 53, 24,  4,  6,  8, 10, 11,  3, 14,
       16, 13, 18,  1, 19, 20, 21, 22, 23, 17,  2, 15,  9, 25, 44,  5,  7,
       12, 32, 26])

In [9]:
indexes = np.argsort(vals)[-10:][::-1]
vals[indexes]

array([ 0.0339686 ,  0.01671703,  0.01552456,  0.00767921,  0.00463245,
        0.00462506,  0.00264161,  0.00233185,  0.00232441,  0.        ])

In [10]:
indexes

array([26, 32, 12,  7,  5, 44, 25,  9, 15,  2])

In [11]:
labels[indexes]

array(['Gruyeres', 'Vevey', 'Engelberg', 'Zweisimmen', 'Lucerne',
       'le Locle', 'Fribourg', 'Lugano', 'Geneva', 'Basel'],
      dtype='<U28')

In [12]:
vals[indexes]

array([ 0.0339686 ,  0.01671703,  0.01552456,  0.00767921,  0.00463245,
        0.00462506,  0.00264161,  0.00233185,  0.00232441,  0.        ])

In [13]:
output = zip(labels[indexes],{'score' : vals[indexes]})

In [14]:
output

In [15]:
import wikipedia
print(wikipedia.page('Rhazuns').content)

Rhäzüns is a municipality in the Imboden Region in the Swiss canton of Grisons.


== History ==
Rhäzüns is first mentioned about 840 as Raezunne. It formed a single parish with Bonaduz until the Reformation. It was part of the Grey League from 1424. It was acquired by the House of Habsburg in 1497 but remained part of the Three Leagues for the purposes of jurisdiction. In the Treaty of Schönbrunn (1809), the Habsburg Monarchy ceded the lordship of Rhäzüns to France. It reverted to Habsburg after the defeat of Napoleon in 1814, but was assigned to Grisons in the Vienna Congress of 1815 (article 78). The transition of administrative power to Grisons, as a canton of the restored Swiss Confederacy, became effective only on 19 January 1819.


== Geography ==

Rhäzüns has an area, as of 2006, of 13.3 km2 (5.1 sq mi). Of this area, 23.3% is used for agricultural purposes, while 69.1% is forested. Of the rest of the land, 4.2% is settled (buildings or roads) and the remainder (3.4%) is non-pro